import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:mondongo/models/consulta.dart';
import 'package:mondongo/services/auth_services.dart';
import 'package:mondongo/services/data_service.dart';
import 'package:auto_route/auto_route.dart';

@RoutePage()
class CustomerQueryPage extends StatefulWidget {
  const CustomerQueryPage({Key? key}) : super(key: key);

  @override
  CustomerQueryPageState createState() => CustomerQueryPageState();
}

class CustomerQueryPageState extends State<CustomerQueryPage> {
  final _formKey = GlobalKey<FormState>();
  final DataService _dataService = GetIt.instance.get<DataService>();
  final AuthService _authService = GetIt.instance.get<AuthService>();

  String _consultaText = '';

  Future<void> _sendConsulta() async {
    if (_formKey.currentState!.validate()) {
      _formKey.currentState!.save();

      final clienteId = _authService.getUser()!.id;
      final mesaNumero = await _getAssignedMesaNumero(clienteId);

      if (mesaNumero == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('No tiene una mesa asignada.')),
        );
        return;
      }

      Consulta consulta = Consulta(
        id: '', // ID will be generated by the database
        mesaNumero: mesaNumero,
        clienteId: clienteId,
        fechaHora: DateTime.now(),
        consulta: _consultaText,
        estado: 'pendiente',
      );

      await _dataService.addConsulta(consulta);

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Consulta enviada al mozo.')),
      );

      Navigator.pop(context);
    }
  }

  Future<int?> _getAssignedMesaNumero(String clienteId) async {
    final pedido = await _dataService.fetchPedidoByClienteId(clienteId);
    return pedido?.mesaNumero;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Consulta al Mozo'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: Column(
            children: [
              Text('Escriba su consulta al mozo:'),
              TextFormField(
                maxLines: 4,
                decoration: InputDecoration(
                  hintText: 'Escriba aquí...',
                  border: OutlineInputBorder(),
                ),
                validator: (value) =>
                    value!.isEmpty ? 'Ingrese su consulta' : null,
                onSaved: (value) => _consultaText = value!,
              ),
              SizedBox(height: 20),
              ElevatedButton(
                onPressed: _sendConsulta,
                child: Text('Enviar Consulta'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
